version: "3"

networks:
  frontend:

services:

  api:
    image: malik393/scaledriven-api:lastest
    container_name: scaledriven-api
    build:
      context: .
      dockerfile: Scaledriven.Api/Dockerfile
    ports:
      - "5001:5001"
    networks:
      - frontend

  web:
    image: malik393/scaledriven-client:lastest
    container_name: scaledriven-client
    build:
      context: .
      dockerfile: Scaledriven.Client/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - frontend

  youtrack:
    image: jetbrains/youtrack:2018.1.41826
    container_name: scaledriven-youtrack
    ports:
      - "8080:8080"
    networks:
      - frontend
    volumes:
      - /opt/youtrack/data
      - /opt/youtrack/conf
      - /opt/youtrack/logs
      - /opt/youtrack/backups
