version: "3"

networks:
  frontend:

services:

  web:
    image: malik393/scaledriven-api:lastest
    container_name: scaledriven
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    networks:
      - frontend

  youtrack:
    image: jetbrains/youtrack:2018.1.41826
    container_name: youtrack
    restart: always
    ports:
      - "8080:8080"
    networks:
      - frontend
    volumes:
      - /opt/youtrack/data
      - /opt/youtrack/conf
      - /opt/youtrack/logs
      - /opt/youtrack/backups
